storeFile = C:\\Users\\ainur\\Desktop\\DECIDE\\key_store_release\\keystore_decide.jks
storePassword = qGRWQE37P5QP
keyAlias = key_decide
keyPassword = XvyihW8g3ARg

VKIDClientSecret=9zAXn29yajqbLukFRvTL
VKIDClientID=52560464